version: '3.5'

services:

    nginx:
      image: ${COMPOSE_PROJECT_NAME}_nginx:latest
      build:
        context: ./docker/
        args:
          - "BUILD_ARGUMENT_ENV=test"
        dockerfile: ./nginx/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_nginx
      restart: always
      ports:
        - 80:80
        - 443:443
      volumes:
        - .:/var/www/html:ro
      depends_on:
        - symfony
      networks:
        - symfony

    symfony: &symfony-template
      image: ${COMPOSE_PROJECT_NAME}_symfony:latest
      build:
        context: .
        args:
          - "BUILD_ARGUMENT_ENV=test"
          - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_symfony
      depends_on:
        - mysql
        - rabbitmq
        - elasticsearch
        - redis
      networks:
        - symfony

    ### Cron tasks, RabbitMQ consumers
    supervisord:
      <<: *symfony-template
      container_name: ${COMPOSE_PROJECT_NAME}_supervisord
      expose: []
      command: ["/usr/bin/supervisord"]

    mysql:
      image: mysql:8.0
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=symfony
      ports:
        - 33061:3306
      volumes:
        - ./var/mysql-data:/var/lib/mysql
        - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      networks:
        - symfony

    rabbitmq:
      image: ${COMPOSE_PROJECT_NAME}_rabbitmq
      build:
        context: ./docker/rabbitmq/
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
      environment:
        - RABBITMQ_ERLANG_COOKIE=7ead507151fc4461b9f45c1161384a04
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        - RABBITMQ_DEFAULT_VHOST=/
      ports:
        - 15672:15672
      volumes:
        - ./var/rabbitmq:/var/lib/rabbitmq
      networks:
        - symfony

    elasticsearch:
      image: ${COMPOSE_PROJECT_NAME}_elasticsearch
      build:
        context: ./docker/
        args:
          - "ELK_VERSION=${ELK_VERSION}"
        dockerfile: ./elasticsearch/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
      environment:
        ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
        ELASTIC_PASSWORD: changeme
        # Use single node discovery in order to disable production mode and avoid bootstrap checks
        # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
        discovery.type: single-node
      ports:
        - 9200:9200
        - 9300:9300
      volumes:
        - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        - ./var/elasticsearch-data:/usr/share/elasticsearch/data
      networks:
        - symfony

    kibana:
      image: ${COMPOSE_PROJECT_NAME}_kibana
      build:
        context: ./docker/
        args:
          - "ELK_VERSION=${ELK_VERSION}"
        dockerfile: ./kibana/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_kibana
      ports:
        - 5601:5601
      volumes:
        - ./docker/test/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      depends_on:
        - elasticsearch
      networks:
        - symfony

    redis:
      image: ${COMPOSE_PROJECT_NAME}_redis
      container_name: ${COMPOSE_PROJECT_NAME}_redis
      build:
        context: ./docker/redis
      restart: always
      networks:
        - symfony

networks:
  symfony:
    name: symfony
